### ISSUE TITLE
Push notifications feature

### ISSUE THREAD

**Issue by chrisK00** [Code2Gether-Discord/subtrack#163]
Feel free to tackle this issue if you want and make the necessary issues. 

The idea is that we want to be able to turn on notifications for every subscription (should be enabled by default if the user has notifications permissions enabled) and select the amount of days before the subscription is due we should be notified. So we need to send a push notification from a background service because the user should be notified even if they dont enter the app unlike the auto-paid which currently runs on startup since it's only relevant when the app is open. We should also notify users if they have missed any payments

**Subtasks**
-    [x]  #170
-    [x] #171
-    [x] #172
-    [x] #173
-    [x] #174

**Todo**
- [x] Mockups for the reminder selector on upsert subscription, docs/mockups.png
- [x] Create issues
- [x] Lookup how to create a background worker in MAUI for android that runs even if app is offline and what permissions are required #167
- [x] Figure out how to send push notifications in MAUI for android #166 and what permissions are required

**Comment by chrisK00** [comment]
added package for sending push notifications in PR #166
